import Navbar from "@/components/Navbar";
import { NavigationMenu } from "@/components/ui/navigation-menu";
import { Metadata } from "next";

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}</body>
    </html>
  );
}
